version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "400:8080"
      - "50000:50000"
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:


    